# Generated by Django 3.0.5 on 2020-07-07 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djaveClassMagic.one_to_one_or_none_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.FloatField(blank=True, default=None, help_text="If this value is set, use it as a permanent zoom value for this user as opposed to dynamically calculating the zoom value based purely on the size of the user's screen.", null=True)),
                ('user', djaveClassMagic.one_to_one_or_none_field.OneToOneOrNoneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
